import { Metadata } from "next";

export const metadata: Metadata = {
  title: { absolute: "store" },
  description: "Generated by create next app",
};

function Store() {
  return <div>Store</div>;
}

export default Store;

// title: { absolute: "store" } is used to set the title of the page to "store" 
// without any additional formatting or template.
// This means that when this page is rendered, the title in the browser tab will simply be "store".