import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // title:"Next"
  title: { default: "Next", template: "%s | sardar" },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header>Root Header</header>
        {children}
        <footer>Root Footer</footer>
      </body>
    </html>
  );
}

// title: { default: "Next", template: "%s | sardar" } is used to
// set the default title of the page to "Next" and also define a template for the title.

// The template "%s | sardar" means that when a specific title is set for a page,
// it will replace the "%s" in the template.

// For example, if a page has a title of "About", the final title in the browser tab will be "About | sardar".

// If no specific title is set for a page, it will default to "Next".
